name: Deploy template-list.json

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install project
        run: |
          npm ci
          npm run generate
          npm run deploy
