name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: npm
      - name: Run test
        run: |
          npm ci
          npm run generate
          npm test
