name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: npm
      - name: Run test
        run: |
          npm ci
          npm run generate
          npm test
