name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: npm
      - name: Run test
        run: |
          npm ci
          npm run generate
          npm test
