name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: npm
      - name: Run test
        run: |
          npm ci
          npm run generate
          npm test
